### ISSUE TITLE
Boefje log4shell not creating KAT objects and sending data to external domain

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-boefjes#14]
### Describe the bug, issue or concern

Currently the log4shell boefje does not create objects that can be used within KAT, but instead seems to send findings to an external domain: https://github.com/minvws/nl-kat-boefjes/blob/410ae0bbfaf4e578f8c09253b47441ff5d7ac5ec/boefjes/plugins/kat_log4shell/main.py#L16

 The description acknowledges this:
https://github.com/minvws/nl-kat-boefjes/blob/410ae0bbfaf4e578f8c09253b47441ff5d7ac5ec/boefjes/plugins/kat_log4shell/boefje.py#L6
although the metadata disagrees:
https://github.com/minvws/nl-kat-boefjes/blob/410ae0bbfaf4e578f8c09253b47441ff5d7ac5ec/boefjes/plugins/kat_log4shell/boefje.py#L8

Organisations hosting KAT for other organisations may have an agreement with the latter to handle scanning results with confidence. The log4shell boefje is not useable in that case. Furthermore, as no objects get created other functionality of KAT does not work properly (such as bits based on the results).

### To Reproduce
1. Use the log4shell boefje.

### Expected behavior
The log4shell boefje creates objects for Octopoes and does not send data to external domains without explicit permission.

**The issue is agnostic to the desktop or smartphone as the problem is in the design of the boefje.**

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by underdarknl** [comment]
Dear @zcrt 
Due to the nature of the way to figure out if there is any log4j present, we need a remote domain to pick up the beacon "pings".
A more useful, and self-hosted solution is being designed for inclusion in KAT.
