### ISSUE TITLE
[OpenKAT v1.6] Add manual created OOI's through Bytes

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-boefjes#67]
Add two normalizers that consume mime types like (not yet determined):

1. manual/ooi
2. manual/csv

Actual mime types are up for discussion. 

Pull requests:

- https://github.com/minvws/nl-kat-rocky/pull/192
- https://github.com/minvws/nl-kat-boefjes/pull/79

**Comment by TwistMeister** [comment]
@Donnype @underdarknl I understood the actual mime types are not yet determined and are still up for discussion.

**Comment by Donnype** [comment]
@underdarknl @Lisser @jpbruinsslot 

I put a bit of thought into this use case and had some thoughts/ideas regarding the goals of this issue.

The goal as I understand is to (be able to) provide a complete audittrail that goes through Bytes, as bytes supports remote timestamping. In the current setup this requires Rocky to create a `BoefjeMeta`, a `RawFile` and wait for the scheduler to start a normalizer and create a `NormalizerMeta`.

This leads to tight coupling between (a workable version of) Rocky and the (local) normalizer workers and the scheduler. It also leads to up to 30 seconds delay for feedback in the interface, which requires frontend work as well (and development work-arounds probably) for a feature that - although very important to get airtight - will make an impact on the usability. What if normalizers are not enabled by default anymore? Do we need create an edge case for manual entries in the plugins? Isn't it a possibility that organizations might want to work without the scheduler at first, or set the pq interval rather high? And what about when the local plugins turn into container images that have to be fetched from a public image repository, then we need to pull from a repository only to create 1 object in the database?

It is also possible to create the `NormalizerMeta` and (still) save Declarations in Rocky. This will reduce this ticket to adding 3 API calls to Bytes to create 3 objects and complete the audit trail, before saving an OOI in Octopoes. I think this could still fix the requirements in the use-case, but with a lot less complexity and coupling.

(This might also relate to/require https://github.com/minvws/nl-rt-tim-abang-bytes/issues/92, and definitely requires https://github.com/minvws/nl-rt-tim-abang/issues/796 and https://github.com/minvws/nl-kat-octopoes/issues/12.)

**Comment by Donnype** [comment]
Update after discussion on the phone with @underdarknl:

We agree on the benefit of such an implementation and that we will add objects in Rocky as well, including the Bytes objects as a first feature. This would then not require any frontend work and still give immediate feedback to the user.

However, we still want to add the normalization code to the boefjes as well in the end for when we need to parse csv files etc. from other resources in the future.
